-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS AS O, ANIMAL_INS AS I
WHERE (O.ANIMAL_ID = I.ANIMAL_ID) AND 
(O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR 
 O.SEX_UPON_OUTCOME LIKE 'Neutered%') AND 
(I.SEX_UPON_INTAKE LIKE 'Intact%')
ORDER BY O.ANIMAL_ID