SELECT 
    SUM(G.SCORE) AS SCORE, -- 총점을 구함
    E.EMP_NO, 
    E.EMP_NAME, 
    E.POSITION, 
    E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = 2022
GROUP BY E.EMP_NO -- 사원 번호로 그룹화
ORDER BY SCORE DESC -- 합산된 점수 기준 내림차순
LIMIT 1;